[tool.ruff]
line-length = 88
target-version = "py311"
exclude = [
  "build",
  "dist",
  ".venv",
  ".git",
  "__pycache__",
  ".venv/**",
  "venv/**",
]

[tool.ruff.lint]
extend-ignore = ["E203"]
extend-select = ["I"]
per-file-ignores = { "custom_components/*/__init__.py" = ["F401"] }

[tool.isort]
profile = "black"
known_first_party = ["ha_daily_counter", "custom_components"]
known_third_party = ["aiohttp", "voluptuous", "homeassistant"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
